apiVersion: v1
kind: Service
metadata:
  name: devops-task5-service
spec:
  selector:
    app: devops-task5
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort